### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by andykuszyk**
Needs a couple of images, and maybe more of a guide as to how the activity runs? What do you think @jzoony @timgarethcarpenter

### CODE REVIEW

**Comment by timgarethcarpenter** [comment]
@andykuszyk really good! I don't think i have any notes to be honest - we;ll written, succinct and to the point.

**Comment by timgarethcarpenter** [comment]
@andykuszyk p.s this is the first time i have used github to any real extent

**Comment by jzoony** [comment]
love it @andykuszyk... wondering if there's any way we can talk about the purpose of a cross functional team and how every participant (Engineer, UX etc.) swapped roles.  The fact a UX designer for example played the part of an Authentication API (for example) gives the designer a good understanding of it's purpose and a much better understanding of architecture in general.

**Comment by andykuszyk** [comment]
Good idea @jzoony . I'll add something along those lines as well as a numbered guide to the activity. Ian is going to send over some images as well.

**Pull request merged**
