### PR TITLE
Guiding principles in a modern workplace

### PR DESCRIPTION
**Pull request by jbentus**

### CODE REVIEW

**Comment by andykuszyk** [comment]
This is fantastic Jose, thank you for your enthusiasm!

**Comment by jbentus** [comment]
It was a pleasure to write it. After I came back from my holiday 3 weeks ago, I was relaxed and got inspired to see all the posts written so far, so I decided to write about this topic and the book I was reading "The Phoenix Project" reflected a bit the reality I found in CF247. @michaelbinks it's your fault basically for lending me the book :D

**Comment by CharlieBarr** [comment]
Great article! whats the next steps for publishing? do the tech leads make the call or is there someone who is responsible for the final sign off?

**Comment by andykuszyk** [comment]
@CharlieBarr we can just merge and see that it appears on the blog ok.

**Pull request merged**
